name: borsh_annotation_extended
description: An extended borsh_annotation library
version: 0.0.1
repository: https://github.com/LimeChain/borsh_annotation_extended

environment:
  sdk: ^3.9.2

dependencies:
  borsh_annotation: ^0.3.2
  solana: ^0.31.2
dev_dependencies:
  lints: ^6.0.0
  test: ^1.17.10
  build_runner: ^2.5.4
  borsh: ^0.3.2
